#Configuration parameters for Einstein Telescope Detector (Triangular) as in bilby. 
#(See https://git.ligo.org/lscsoft/bilby/-/blob/master/bilby/gw/detector/detectors/ET.interferometer?ref_type=heads)"

E2: 
    latitude           : 40.443 #43.716283275958006 
    longitude          : 9.457 #10.545780315644306
    elevation          : -100.0 #51.884
    arms_orientation   : 60.0
    angle_between_arms : 60.0

    #xarm_azimuth       : 190.56739999996796
    #yarm_azimuth       : 250.5674000001629
    #angle_between_arms : 60.0
