
#Configuration parameters for Einstein Telescope Detector (Triangular) as in bilby. 
#(See https://git.ligo.org/lscsoft/bilby/-/blob/master/bilby/gw/detector/detectors/ET.interferometer?ref_type=heads)"

E2: 
    latitude           : 40.443 #43.69975646133719
    longitude          : 9.457 #10.423819293243076
    elevation          : -100.0 #51.884
    arms_orientation   : 120.0
    angle_between_arms : 60.0


    #xarm_azimuth       : 310.5673999997849
    #yarm_azimuth       : 10.567399999979784
    #angle_between_arms : 60.0
